=== initialb/CrazyJava/project_codes/IoC/main/org/crazyit/ioc/beans/beans.dtd
<!ELEMENT beans (
	bean*
)>
<!ATTLIST beans default-lazy-init (true | false) "false">
<!ATTLIST beans default-autowire (no | byName) "no">
<!-- 指定beans元素的子元素bean -->
<!ELEMENT bean (
	(constructor-arg | property)*
)>
<!-- 指定bean元素的属性值 -->
<!ATTLIST bean id CDATA #REQUIRED>
<!ATTLIST bean class CDATA #REQUIRED>
<!ATTLIST bean lazy-init (true | false | default) "default">
<!ATTLIST bean singleton (true | false) "true">
<!ATTLIST bean autowire (no | byName | default) "default">
<!-- 声明constructor-arg元素 -->
<!ELEMENT constructor-arg (
	(ref | value | null)
)>
<!-- 声明property元素 -->
<!ELEMENT property (
	(ref | value | null)?
)>
<!-- 声明property的name属性 -->
<!ATTLIST property name CDATA #REQUIRED>
<!-- 声明value的type属性 -->
<!ATTLIST value type CDATA #REQUIRED>
<!-- 声明ref元素 -->
<!ELEMENT ref EMPTY>
<!-- 声明ref的bean属性 -->
<!ATTLIST ref bean CDATA #REQUIRED>

<!-- 声明value元素 -->
<!ELEMENT value (#PCDATA)>

=== initialb/CrazyJava/project_codes/book(IoC)/bin/resource/daoContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//CRAZYIT//DTD BEAN//EN" "http://www.crazyit.org/beans.dtd">
<beans>
	<!-- DAO -->
	<!-- 用户的dao -->
	<bean id="userDao" class="org.crazyit.book.dao.impl.UserDaoImpl"></bean>
	<!-- 用户的业务接口, 使用设值注入 -->
	<!-- 书本种类DAO -->
	<bean id="typeDao" class="org.crazyit.book.dao.impl.TypeDaoImpl"></bean>
	<!-- 出版社DAO -->
	<bean id="concernDao" class="org.crazyit.book.dao.impl.ConcernDaoImpl"></bean>
	<!-- 书本DAO -->
	<bean id="bookDao" class="org.crazyit.book.dao.impl.BookDaoImpl"></bean>
	<!-- 销售DAO -->
	<bean id="saleRecordDao" class="org.crazyit.book.dao.impl.SaleRecordDaoImpl"></bean>
	<!-- 书本销售DAO -->
	<bean id="bookSaleRecordDao" class="org.crazyit.book.dao.impl.BookSaleRecordDaoImpl"></bean>
	<!-- 入库DAO -->
	<bean id="inRecordDao" class="org.crazyit.book.dao.impl.InRecordDaoImpl"></bean>
	<!-- 书本入库DAO -->
	<bean id="bookInRecordDao" class="org.crazyit.book.dao.impl.BookInRecordDaoImpl"></bean>
</beans>

=== initialb/CrazyJava/project_codes/IoC/test/resources/ElementReader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//CRAZYIT//DTD BEAN//EN" "http://www.crazyit.org/beans.dtd">

<beans>
	<!-- isLazy方法 -->
	<bean id="test1-1" class="org.crazyit.ioc.xml.TestObject1" lazy-init="true"></bean>
	<bean id="test1-2" class="org.crazyit.ioc.xml.TestObject1" lazy-init="default"></bean>
	<bean id="test1-3" class="org.crazyit.ioc.xml.TestObject1" lazy-init="false"></bean>
	<!-- getConstructorElements方法 -->
	<bean id="test2" class="org.crazyit.ioc.xml.TestObject1">
		<constructor-arg>
			<value type="java.lang.String">yangenxiong</value>
		</constructor-arg>
		<constructor-arg>
			<value type="java.lang.String">crazyit</value>
		</constructor-arg>
	</bean>
	<!-- getAttribute方法 -->
	<bean id="test3" class="org.crazyit.ioc.xml.TestObject1"></bean>
	<!-- isSingleton方法 -->
	<bean id="test4-1" class="org.crazyit.ioc.xml.TestObject1" singleton="false"></bean>
	<bean id="test4-2" class="org.crazyit.ioc.xml.TestObject1"></bean>
	<!-- getConstructorArgs方法 -->
	<bean id="test5" class="org.crazyit.ioc.xml.TestObject1">
		<constructor-arg>
			<value type="java.lang.String">yangenxiong</value>
		</constructor-arg>
		<constructor-arg>
			<value type="java.lang.String">crazyit</value>
		</constructor-arg>
	</bean>
	<!-- getPropertyElements方法 -->
	<bean id="test6" class="org.crazyit.ioc.xml.TestObject1">
		<property name="test1">
			<ref bean="test1"/>
		</property>
		<property name="test2">
			<ref bean="test2"/>
		</property>
	</bean>
	<!-- getPropertyValues方法 -->
	<bean id="test7" class="org.crazyit.ioc.xml.TestObject1">
		<property name="test1">
			<value type="java.lang.String">yangenxiong</value>
		</property>
		<property name="test2">
			<value type="java.lang.String">crazyit</value>
		</property>
	</bean>
	<!-- getPropertyRef方法 -->
	<bean id="test8" class="org.crazyit.ioc.xml.TestObject1">
		<property name="test1">
			<ref bean="test1"/>
		</property>
		<property name="test2">
			<ref bean="test2"/>
		</property>
	</bean>
	
	<!-- getConstructorRef方法 -->
	<bean id="test9" class="org.crazyit.ioc.xml.TestObject1">
		<constructor-arg>
			<ref bean="test1"/>
		</constructor-arg>
		<constructor-arg>
			<ref bean="test2"/>
		</constructor-arg>
	</bean>
	
	<!-- isAutowire方法 -->
	<bean id="test10-1" class="org.crazyit.ioc.xml.TestObject1" autowire="byName">
	</bean>
	<bean id="test10-2" class="org.crazyit.ioc.xml.TestObject1" autowire="no">
	</bean>
	<bean id="test10-3" class="org.crazyit.ioc.xml.TestObject1" autowire="default">
	</bean>
	
	<!-- getConstructorValue方法 -->
	<bean id="test11" class="org.crazyit.ioc.xml.TestObject1">
		<constructor-arg>
			<value type="java.lang.String">yangenxiong</value>
		</constructor-arg>
		<constructor-arg>
			<ref bean="test2"/>
		</constructor-arg>
		<constructor-arg>
			<value type="java.lang.Integer">20</value>
		</constructor-arg>
	</bean>
	
	<!-- getPropertyValue方法 -->
	<bean id="test12" class="org.crazyit.ioc.xml.TestObject1">
		<property name="property1">
			<value type="java.lang.String">yangenxiong</value>
		</property>
		<property name="property2">
			<ref bean="test13"/>
		</property>
		<property name="property3">
			<value type="java.lang.Integer">20</value>
		</property>
	</bean>
	<bean class="org.crazyit.ioc.xml.TestObject2" id="test13"></bean>
</beans>

=== initialb/CrazyJava/project_codes/book(IoC)/src/resource/serviceContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//CRAZYIT//DTD BEAN//EN" "http://www.crazyit.org/beans.dtd">
<beans>
	<!-- Service，在这里使用自动装配 -->
	<!-- 用户service使用设值注入，不自动装配 -->
	<bean id="userService" class="org.crazyit.book.service.impl.UserServiceImpl">
		<property name="userDao">
			<ref bean="userDao"/>
		</property>
	</bean>
	<!-- 种类service -->
	<bean id="typeService" class="org.crazyit.book.service.impl.TypeServiceImpl" autowire="byName"></bean>
	<!-- 出版社service -->
	<bean id="concernService" class="org.crazyit.book.service.impl.ConcernServiceImpl" autowire="byName"></bean>
	<!-- 书本service -->
	<bean id="bookService" class="org.crazyit.book.service.impl.BookServiceImpl" autowire="byName"></bean>
	<!-- 销售service -->
	<bean id="saleRecordService" class="org.crazyit.book.service.impl.SaleRecordServiceImpl" autowire="byName"></bean>
	<!-- 入库service -->
	<bean id="inRecordService" class="org.crazyit.book.service.impl.InRecordServiceImpl" autowire="byName"></bean>
</beans>

=== initialb/CrazyJava/project_codes/book(IoC)/bin/resource/uiContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//CRAZYIT//DTD BEAN//EN" "http://www.crazyit.org/beans.dtd">

<beans>

	<!-- 界面对象 -->
	<!-- 登录界面, 同时使用构造注入和设值注入 -->
	<bean id="loginFrame" class="org.crazyit.book.ui.LoginFrame">
		<!-- 通过构造注入, 向LoginFrame注入userService(用户业务接口) -->
		<constructor-arg>
			<ref bean="userService"/>
		</constructor-arg>
		<!-- 通过设值注入方式, 向LoginFrame对象注入MainFrame的bean -->
		<property name="mainFrame">
			<ref bean="mainFrame"/>
		</property>
	</bean>
	<!-- 
		主界面MainFrame的bean，需要进行构造注入，由于初始化界面的时候，需要设置当前界面为销售界面，
		除了SalePanel外，其他界面对象通过自动装配初始化
	 -->
	<bean id="mainFrame" class="org.crazyit.book.ui.MainFrame" autowire="byName">
		<constructor-arg>
			<ref bean="salePanel"/>
		</constructor-arg>
	</bean>
	<!-- 各个界面对象(JPanel对象)，在这里使用构造注入，因为在创建这些对象时，需要初始化数据，数据是从业务层得到的 -->
	<!-- 销售JPanel -->
	<bean id="salePanel" class="org.crazyit.book.ui.SalePanel">
		<constructor-arg>
			<ref bean="bookService"/>
		</constructor-arg>
		<constructor-arg>
			<ref bean="saleRecordService"/>
		</constructor-arg>
	</bean>
	<!-- 库存JPanel -->
	<bean id="repertoryPanel" class="org.crazyit.book.ui.RepertoryPanel">
		<constructor-arg>
			<ref bean="inRecordService"/>
		</constructor-arg>
		<constructor-arg>
			<ref bean="bookService"/>
		</constructor-arg>
	</bean>
	<!-- 书本JPanel -->
	<bean id="bookPanel" class="org.crazyit.book.ui.BookPanel">
		<constructor-arg>
			<ref bean="bookService"/>
		</constructor-arg>
		<constructor-arg>
			<ref bean="typeService"/>
		</constructor-arg>
		<constructor-arg>
			<ref bean="concernService"/>
		</constructor-arg>
	</bean>
	<!-- 出版社JPanel -->
	<bean id="concernPanel" class="org.crazyit.book.ui.ConcernPanel">
		<constructor-arg>
			<ref bean="concernService"/>
		</constructor-arg>
	</bean>
	<!-- 种类JPanel -->
	<bean id="typePanel" class="org.crazyit.book.ui.TypePanel">
		<constructor-arg>
			<ref bean="typeService"/>
		</constructor-arg>
	</bean>
</beans>

=== initialb/CrazyJava/project_codes/IoC/target/resources/context/XmlApplicationContext1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//CRAZYIT//DTD BEAN//EN" "http://www.crazyit.org/beans.dtd">

<beans >
	<bean id="test1" class="org.crazyit.ioc.context.object.XmlApplicationContextObject1"></bean>
	
	<bean id="test2" class="org.crazyit.ioc.context.object.XmlApplicationContextObject2">
		<constructor-arg>
			<value type="java.lang.String">yangenxiong</value>
		</constructor-arg>
		<constructor-arg>
			<value type="java.lang.Integer">10</value> 
		</constructor-arg>
		<constructor-arg>
			<ref bean="test1"/> 
		</constructor-arg>
	</bean>
	
	<bean id="test3" 
	class="org.crazyit.ioc.context.object.XmlApplicationContextObject1" singleton="false">
	
	</bean>
	
	<!-- 测试autowire -->
	<bean class="org.crazyit.ioc.context.object.XmlApplicationContextObject1" 
		id="object1">
	</bean>
	<bean id="test4" 
		class="org.crazyit.ioc.context.object.XmlApplicationContextObject3" 
		autowire="byName">
	</bean>
	<!-- 测试lazy-init -->
	<bean id="test5" class="org.crazyit.ioc.context.object.XmlApplicationContextObject3" lazy-init="true">
	</bean>
	
	<!-- 测试设值注入 -->
	<bean id="test6" class="org.crazyit.ioc.context.object.XmlApplicationContextObject3">
		<property name="name">
			<value type="java.lang.String">yangenxiong</value>
		</property>
		<property name="age">
			<value type="java.lang.Integer">10</value>
		</property>
		<property name="object1">
			<ref bean="object1"/>
		</property>
	</bean>
</beans>
